taxa_page:
  overview:
    panels:
      - - - panel:gallery
          - panel:type
          - panel:type-specimen
          - panel:nomenclature
          - panel:nomenclature-references

        - - panel:map
          - panel:statistics
          - panel:content
          - panel:descendants

  specimen_record:
    rank_group: ['SpeciesGroup']
    panels:
      - - - panel:specimen-records
  iNaturalist:
    label: 'iNaturalist'
    rank_group: ['GenusGroup', 'SpeciesGroup']
    panels:
      - - - panel:inaturalist
